### PR TITLE
Please, accept these changes

### PR DESCRIPTION
**Pull request by Paphra**
Finished working on the builtin command ```env```
- I have checked for memory leaks and found none
- Am going to try the checker you have given from the repo and see how it works, if i notice problems, am also going to try and sort them.

**Moving forward: **
- Am going to start working on ```strtok``` custom function that we don't use the one that comes from ```string.h```

### CODE REVIEW

**Comment by Paphra** [comment]
I might also handle the ```cd``` command

**Comment by bravemaster3** [comment]
Thanks for the PR

**Comment by Paphra** [comment]
I have noticed that handling ```cd``` requires one to handle ```setenv``` and ```unsetenv``` before ```cd```

**Comment by bravemaster3** [comment]
Okay. Then I guess if strtok doesn't take you too much time you should start looking at setenv and unsetenv then.
I might be able to implement getline if I get time before our meeting.

**Comment by Paphra** [comment]
Alright. But the ```Insights``` is now showing me as done one and then also two commits, like it was showing for you

**Comment by Paphra** [comment]
How did you solve that?

**Comment by bravemaster3** [comment]
I did so many things, and it is difficult to ascertain what worked.
If this is only from the last commit, then

`git commit --amend --author="Author Name <email@address.com>"`

But first, do git log to confirm that you have a different email address in your last commit.
If that is the case, then manybe you want to change also things in your git config.
After doing all that the amend, I pushed, but in my case I had to also remove commits from the other me...

But I can't remember exacly how I did. Sorry.
Try, and if you don't manage I can try later as well.

**Comment by Paphra** [comment]
I have managed to solve the issues locally,
Please, turn off the protection on the main for just a short while and I push the amended history to main

**Pull request merged**
